### ISSUE TITLE
Default Version of CTRE doesn't include new methods

### ISSUE THREAD

**Issue by 20JatinK** [Open-RIO/GradleRIO#101]
At first my code didn't compile, then after a lot of hard work and time I figured out that the default dependency for CTRE uses version 5.2.2.0 instead of 5.3.1.0. Changing this would have saved me so much time for setting Gradle RIO up.

**Comment by JacisNonsense** [comment]
This is intentional, see here: https://github.com/Open-RIO/GradleRIO/issues/79
