### ISSUE TITLE
2016 release

### ISSUE THREAD

**Issue by Andrew-Dickinson** [Open-RIO/GradleRIO#12]
Are you planning to create a release with support for the latest WPI libraries? I see the commit, are you waiting before you create a release?

**Comment by JacisNonsense** [comment]
GradleRIO 2016 Releases are currently uploaded. GradleRIO 4.0.2 is the current version, and can be updated by running `gradlew tasks --refresh-dependencies`

**Comment by Andrew-Dickinson** [comment]
I see. You may want to include a "Release" on the github "Releases" system to make this clear.

**Comment by JacisNonsense** [comment]
The releases don't change, but instead is a template for getting started with a gradle project. I may add a repo tag or something, though
