### ISSUE TITLE
"Examples" link in README.md is broken

### ISSUE THREAD

**Issue by blerchy** [Open-RIO/GradleRIO#20]
In the README, under Features>Dependency Management, there is a link to examples leading to the URL `https://github.com/Open-RIO/GradleRIO/blob/master/examples` which results in a 404.

**Comment by blerchy** [comment]
Here's a link to jump straight to the relevant section: https://github.com/Open-RIO/GradleRIO#dependency-management

**Comment by JacisNonsense** [comment]
Examples aren't up yet. I'll be putting them in once #17 is fully stable
