### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by bob80333** [Open-RIO/GradleRIO#22]
After updating my team's roboRio to the 2017 firmware and updating our router, I tried to deploy and got this error message:

`Failed SFTP PUT: C:\Users\Jared\IdeaProjects\SammyRoboRio\build\libs\SammyRoboRio.jar -> Remote21:/home/lvuser`

[Stacktrace](https://hastebin.com/izilusoqug.vbs)
[build.gradle](https://hastebin.com/gihefupisi.http)

**Comment by 19lmyers** [comment]
The same EXACT thing is happening to me, except it's called Remote3.

**Comment by bob80333** [comment]
The number kept incrementing as I kept trying to deploy

**Comment by JacisNonsense** [comment]
You need to run `./gradlew build` before `./gradlew deploy`, i.e. `./gradlew build deploy`. This was a change made during the 2016-2017 migration to decouple building and deploying

**Comment by bob80333** [comment]
OK, thanks
