### ISSUE TITLE
/usr/bin/env 'bash\r': No such file or directory

### ISSUE THREAD

**Issue by rolylolypoly** [Open-RIO/GradleRIO#23]
Kubuntu 16.04 LTS.
Fixed by running gradlew through dos2unix.

**Comment by JacisNonsense** [comment]
Which `gradlew` is this from, quickstart?

**Comment by rolylolypoly** [comment]
Yeah quickstart.

**Comment by JacisNonsense** [comment]
The file seems fine on my end, it seems like it's because the quickstart project was zipped on a windows machine.

**Comment by tkdberger** [comment]
I just downloaded the latest quickstart and am having this same issue.

**Comment by JacisNonsense** [comment]
Sorry, usually this happens when I commit from my desktop. I've added a new commit to fix that. I'll set up some automated system in the future since it's such a recurring issue
