### ISSUE TITLE
Version 2017.1.1 of jaci.openrio.gradle.GradleRIO Doesn't Have "toastDeploy" Task

### ISSUE THREAD

**Issue by rtielking** [Open-RIO/GradleRIO#27]
On Mac El Capitan, when I run "gradlew tasks", there is no "toastDeploy" task listed. Not sure if this is a mistake or the method to deploy toast to roborio has changed.

build.gradle file looks like:

plugins {
id "java"
id "eclipse"
id "idea"
id "jaci.openrio.gradle.GradleRIO" version "2017.1.1"
}

repositories {
mavenCentral()
}

frc {
team = "4330"
robotClass = "frc.team4330.screambunction.RobotModule"
}

dependencies {
compile fileTree(dir: "libs", include: "*.jar")
compile group: 'jaci.openrio.toast', name: 'Toast', version: '+'
testCompile 'junit:junit:4.12'
}

def robotManifest = {
attributes 'Main-Class': 'edu.wpi.first.wpilibj.RobotBase'
attributes 'Robot-Class': frc.robotClass
}

jar {
from (zipTree('libs/navx_frc.jar')) {
include '**/*.class'
}
manifest robotManifest
}

task wrapper(type: Wrapper) {
gradleVersion = '3.2.1'
}

**Comment by JacisNonsense** [comment]
Please see the [Toast README](https://github.com/Open-RIO/ToastAPI#wheres-the-2017-update)
