### ISSUE TITLE
nativeZip behavior changed

### ISSUE THREAD

**Issue by WawerOS** [Open-RIO/GradleRIO#35]
nativeZip complains that it can't resolve  cscore-1.0.2-athena-uberzip.zip, we used to be able to placate it with a copy in libs/ and using --offline but it now complains again.

**Comment by WawerOS** [comment]
I have confirmed using wget and curl that GET works for the repository.

**Comment by JacisNonsense** [comment]
You shouldn't be placing any WPI core library in your own libs/ file. GradleRIO manages this [for you](https://github.com/Open-RIO/GradleRIO/blob/master/src/main/groovy/jaci/openrio/gradle/wpi/WPIPlugin.groovy#L59-L64)

**Comment by WawerOS** [comment]
Could that be the problem? Cause gradlerio also stalls getting the appropriate library, all others download fine.

**Comment by JacisNonsense** [comment]
Does the same issue occur if you remove your cscore loaded in libs/, and set `wpi.cscoreVersion="1.0.1"` ?

**Comment by JacisNonsense** [comment]
Also a proper log would be useful
