### ISSUE TITLE
Dependencies not resolving

### ISSUE THREAD

**Issue by WawerOS** [Open-RIO/GradleRIO#4]
I'm trying to set up  GradleRIO but whenever I run ./gradlew  it errors saying 

* What went wrong:
A problem occurred configuring root project 'gradle-prototype'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find jaci.openrio.gradle:GradleRIO:1.1.5.
     Searched in the following locations:
         https://repo1.maven.org/maven2/jaci/openrio/gradle/GradleRIO/1.1.5/GradleRIO-1.1.5.pom
         https://repo1.maven.org/maven2/jaci/openrio/gradle/GradleRIO/1.1.5/GradleRIO-1.1.5.jar
         http://dev.imjac.in/maven/jaci/openrio/gradle/GradleRIO/1.1.5/GradleRIO-1.1.5.pom
         http://dev.imjac.in/maven/jaci/openrio/gradle/GradleRIO/1.1.5/GradleRIO-1.1.5.jar
     Required by:
         :gradle-prototype:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I tried manually adding dependencies but ./gradlew doesn't seem to look at them.

**Comment by JacisNonsense** [comment]
This looks like an issue in your build.gradle file. Try changing the line that reads similar to:
```
classpath group: 'jaci.openrio.gradle', name: 'GradleRIO', version: '1.3.0'
```  
to 
```
classpath group: 'jaci.openrio.gradle', name: 'GradleRIO', version: '+'
```

This should cause gradle to automatically grab the latest GradleRIO release, which at the time is 2.0.1

**Comment by WawerOS** [comment]
Thanks!!
