### ISSUE TITLE
Support for directory-based structure

### ISSUE THREAD

**Issue by andriyasdf** [Open-RIO/GradleRIO#40]
GradleRIO should drop file-based project structure support when generating a new project and instead use directory-based. This would make it easier for version control to manage, as files are split up into smaller segments.

**Comment by JacisNonsense** [comment]
Can you give me a better idea of what you're suggesting? Are you talking about Gradle project, Eclipse project, IntelliJ projects, or something else? Examples would be appreciated

**Comment by andriyasdf** [comment]
Whoops, I meant to specify that I’m talking about IntelliJ projects. When running the command “gradlew idea,” it would be ideal if this generates a directory-based project instead. Can GradleRIO support this format?

**Comment by andriyasdf** [comment]
Now looking at the IDEA plugin for Gradle, I'm assuming you don't have much control over this process. I guess we'll have to wait and see what gradle decides to do.

**Comment by JacisNonsense** [comment]
You can still make that kind of thing happen with multi-project builds. Just include the 'idea' plugin in all your projects, and run `./gradlew idea` from the root project. That'll generate an idea project that includes an idea module for each subproject. We did it in 2016 [here](https://github.com/FRC5333/2016-Champs)
