### ISSUE TITLE
Clarify Telemetry

### ISSUE THREAD

**Issue by bdaroz** [Open-RIO/GradleRIO#59]
It would probably be best before kickoff if it was made clear (perhaps in `README.md`) what the telemetry captures, and how it is used. (Eg a privacy policy)

**Comment by JacisNonsense** [comment]
Sure thing, it's been on the todo list to add a PRIVACY.md linking from the README. If you're every concerned about what exactly telemetry reports, you can run `./gradlew telemetry`, which prints out the telemetry report. You can also see the [server-side code](https://github.com/JacisNonsense/imjac.in_ta/blob/master/modules/openrio/openrio_library.rb) also, the logic is all completely open.
