### ISSUE TITLE
GradleRIO pulls in incorrect version of Shuffleboard

### ISSUE THREAD

**Issue by 19lmyers** [Open-RIO/GradleRIO#60]
I was having an issue with Shuffleboard and it turns out GradleRIO 2018.01.06 is pulling in Shuffleboard 0.3.0 instead of the proper 1.0.0, even when I change the shuffleboardVersion property in the wpi block to 1.0.0?

**Comment by JacisNonsense** [comment]
You are correct, it looks like the maven artifact has changed. I'll fix this tonight

**Comment by JacisNonsense** [comment]
Nevermind, fixed in 2018.01.06a just now
