### ISSUE TITLE
Add Javadocs for commonly-used libraries

### ISSUE THREAD

**Issue by aswerdlow935** [Open-RIO/GradleRIO#63]
I'm not sure if this is something that can be done from gradle, but adding the javadocs along with the existing source files would be super helpful. (for intellij at least) I can manually add the javadoc, but with constant library updates and several computers, adding the javadoc would be super useful

**Comment by JacisNonsense** [comment]
The JavaDocs are already made available.

IntelliJ will prefer to use provided sources over javadocs, so if you run `./gradlew idea`, it will link both the compiled jar and the sources jar. If you inspect a library class, you can still view the comments of the class.

![](https://puu.sh/yVg4X/0e8a1d1abf.png)

**Comment by aswerdlow935** [comment]
Ha yes I saw that...I was talking about the *javadoc* javadoc that opens in a browser...but then again maybe I'm the only person who uses the open external documentation feature instead of built-in hower to preview. For some reason Intellij doesn't want to generate it and needs a javadoc link/file

**Comment by JacisNonsense** [comment]
I think this is a close. If you want to see the javadoc in a browser, all vendors appear to publish their javadocs online that you can view.
