### ISSUE TITLE
Code too large error

### ISSUE THREAD

**Issue by aswerdlow935** [Open-RIO/GradleRIO#68]
Getting a 'code to large error' with java files over ~1000-1500 lines. Not sure if it's a gradleRIO limitation or roboRIO one. (The large file is a pregenerated trajectory as a large array in a java class)

**Comment by JacisNonsense** [comment]
Send me a copy of the error message

**Comment by JacisNonsense** [comment]
This actually seems to be an error in java, not gradle (Google 'code too large java'). For large trajectories, store them in another file that you can decode at runtime, like a csv
