### ISSUE TITLE
Compiler args caching on Windows

### ISSUE THREAD

**Issue by spacey-sooty** [Open-RIO/GradleRIO#691]
Within our `build.gradle` we had these lines 
```groovy
binaries.all {
  cppCompiler.args "-Werror"
  cppCompiler.args "-Wextra"
  cppCompiler.args "-Wall"
  cppCompiler.args "-pedantic"
}
```
Obviously this would break simulation on Windows. So we removed this in our `build.gradle` on Windows, but when we recompile we still get the same issue. We have tried clean building and making changes to our main code as well but the error persists.

**Comment by ThadHouse** [comment]
Do you have a link to the project? Theres no way after a clean those should be cached.

**Comment by ThadHouse** [comment]
Did the student remove them from both the root project and the wombat project? Also did they do separate clones from both windows and wsl? You can’t build from the wsl directory natively in windows, and from a windows directory in wsl. They have to be separate.

**Comment by spacey-sooty** [comment]
They definitely removed them from the root and Wombat projects. There was only one local repo which was being used from both WSL and Windows.
