### ISSUE TITLE
Build fails after switching from Wifi deploy to USB deploy when running with the Gradle daemon

### ISSUE THREAD

**Issue by jrmihalick** [Open-RIO/GradleRIO#72]
Steps to reproduce:

1) Make sure the gradle daemon is enabled
2) Connect to the RoboRio over Wifi
3) Run a `gradle deploy`.  The code should successfully deploy to the robot.
4) Disconnect from Wifi and connect to the RoboRio over USB (172.22.11.2).
5) Run a `gradle deploy`.  GradleRIO will attempt to again to deploy over Wifi, but it should instead attempt to use the USB connection.  The build will fail.  See attached debug.txt output.

If you disable the gradle daemon (for example using the `--no-daemon` command line option), the problem does not occur.

I think the same problem also occurs when switching from first deploying over USB, then deploying to Wifi.
[debug.txt](https://github.com/Open-RIO/GradleRIO/files/1649202/debug.txt)

**Comment by JacisNonsense** [comment]
I'll take a look at this when I have a RoboRIO tomorrow. It looks to me like in EmbeddedTools, the addressStorage buffer isn't being cleared upon new builds, so I'll add a hook to erase it if necessary. https://github.com/JacisNonsense/EmbeddedTools/blob/master/src/main/groovy/jaci/gradle/deploy/tasks/TargetDiscoveryTask.groovy
