### ISSUE TITLE
Wrong Maven Url

### ISSUE THREAD

**Issue by 333fred** [Open-RIO/GradleRIO#8]
Please use the release version of the Maven repo, not development. Development is always the latest builds off of master, whereas release is the official version shipped with the plugins. The correct url is http://first.wpi.edu/FRC/roborio/maven/release.

**Comment by JacisNonsense** [comment]
On my last check the 'release' maven was missing some artifacts (networktables ARM iirc). Has this been resolved?

**Comment by 333fred** [comment]
They're all there. The artifacts are copied from our build server to the web-accessible repo, so you might have checked before they were fully finished copying.

**Comment by 333fred** [comment]
If you do notice something missing, please let me know.

**Comment by JacisNonsense** [comment]
Okay, sounds good to me. Will merge :+1:
