### ISSUE TITLE
Execution failed for task ':deployFrcNative'

### ISSUE THREAD

**Issue by StripedMonkey** [Open-RIO/GradleRIO#82]
During Comps I discovered this issue and ended up having to use eclipse to deploy.
[ErrorGradleRIO.txt](https://github.com/Open-RIO/GradleRIO/files/1823010/ErrorGradleRIO.txt)

Any clues as to who/what/why? This is an issue only with deploying.

**Comment by JacisNonsense** [comment]
Please run with `--debug` and send the full log. 

Have you run on MINGW before this? We don't officially support it

**Comment by JacisNonsense** [comment]
Can you list the files present in `C:\Users\HP Owner\Projects\20186214\build\exe\frcUserProgram\` with `ls -al` ?

**Comment by StripedMonkey** [comment]
It appears to be empty.
```bash
 ls -al build/exe/frcUserProgram/
total 0
drwxr-xr-x 1 HP Owner 197121 0 Mar 21 16:17 ./
drwxr-xr-x 1 HP Owner 197121 0 Mar 21 16:17 ../
```

**Comment by StripedMonkey** [comment]
I just tried it with powershell and both the gradlew & gradlew.bat and nether appear to work.

**Comment by JacisNonsense** [comment]
You've run `./gradlew installToolchain`, right?

**Comment by StripedMonkey** [comment]
Correct

**Comment by StripedMonkey** [comment]
There *is* a connection to the RoboRIO by the way, when deploying code using GradleRIO it will kill the code currently on the robot and will not come back until you deploy using the Eclipse Plugin

**Comment by JacisNonsense** [comment]
Given a build file isn't being generated, this sounds like an issue with MINGW. Run ./gradlew build --debug --console=plain and send me the output

**Comment by StripedMonkey** [comment]
Tbh I'm not sure why that would be. It compiles fine and deploys without issue using the eclipse plugin. Additionally (you know far more than me btw, this is all me trying to understand it) doesn't the "installtoolchain" and the wpilib thing cover everything nessicary to build and compile?

I'll test it out ASAP but unfortunately comps are this weekend for me so I'll be a bit tied up.

**Comment by JacisNonsense** [comment]
The toolchain isn't shared between MINGW and your windows system, it likely won't work on mingw which is why we don't officially supported. If gradle can't find the toolchain, we've told it to skip the build.

The wpilib toolchain and `installToolchain` install the toolchain to different directories. If you want to build and deploy, don't use mingw since it probably won't work, use cmd/powershell instead

**Comment by StripedMonkey** [comment]
I've tried Powershell though and it gave the same error.

**Comment by JacisNonsense** [comment]
In that case, try `./gradlew components` and show me the output. For some reason, it isn't producing a binary

**Comment by StripedMonkey** [comment]
I managed to figure out the issue, apparently I don't have my second directories properly configured. 

I don't have my program structured in the src/cpp src/headers format.
