### ISSUE TITLE
Adds simulation native libraries to Java test task

### ISSUE THREAD

**Issue by ThadHouse** [Open-RIO/GradleRIO#93]
We should enable usage of the `test` task. In order to properly do this, we need to either add all the native libraries to the runtime path of the test task. On linux and mac, this can be done with `LD_LIBRARY_PATH` and `-Djava.library.path`. On windows, you need `-Djava.library.path`, along with adding all of the native libraries to the system path. We should not use the JNI jars for anything GradleRIO related, as especially on windows they have issues.

**Comment by JacisNonsense** [comment]
Closed in #0ab7dc8
